-- MySQL Script generated by MySQL Workbench
-- Wed Jan 18 15:08:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Plateforme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plateforme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`communauté`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`communauté` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amis` VARCHAR(45) NULL DEFAULT NULL,
  `en_ligne` VARCHAR(45) NULL DEFAULT NULL,
  `hors_ligne` VARCHAR(45) NULL DEFAULT NULL,
  `amis_bloqués` VARCHAR(45) NULL DEFAULT NULL,
  `jeux_en_cours` VARCHAR(45) NULL DEFAULT NULL,
  `chat` VARCHAR(45) NULL DEFAULT NULL,
  `statut` VARCHAR(45) NULL DEFAULT NULL,
  `profil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bibliothèque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bibliothèque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jeux_téléchargés` VARCHAR(45) NULL DEFAULT NULL,
  `jeux_achetés` VARCHAR(45) NULL DEFAULT NULL,
  `historique_dachat` VARCHAR(45) NULL DEFAULT NULL,
  `ajout_jeux` VARCHAR(45) NULL DEFAULT NULL,
  `suppr_jeux` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `naissance` DATETIME NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  `image-avatar` VARCHAR(255) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  `enligne_id` VARCHAR(45) NULL DEFAULT NULL,
  `communauté_id` INT NULL DEFAULT NULL,
  `bibliothèque_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `mdp_UNIQUE` (`mdp` ASC),
  UNIQUE INDEX `adresse_UNIQUE` (`adresse` ASC),
  INDEX `fk_utilisateur_communauté1_idx` (`communauté_id` ASC),
  INDEX `fk_utilisateur_bibliothèque1_idx` (`bibliothèque_id` ASC),
  CONSTRAINT `fk_utilisateur_communauté1`
    FOREIGN KEY (`communauté_id`)
    REFERENCES `mydb`.`communauté` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_bibliothèque1`
    FOREIGN KEY (`bibliothèque_id`)
    REFERENCES `mydb`.`bibliothèque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jeux` VARCHAR(45) NULL DEFAULT NULL,
  `reçu` VARCHAR(45) NULL DEFAULT NULL,
  `historique` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `jeux_UNIQUE` (`jeux` ASC),
  UNIQUE INDEX `reçu_UNIQUE` (`reçu` ASC),
  UNIQUE INDEX `historique_UNIQUE` (`historique` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jeux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jeux` (
  `idjeux` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `age conseillé` VARCHAR(45) NULL DEFAULT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `video` VARCHAR(45) NULL DEFAULT NULL,
  `download` VARCHAR(45) NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `Plateforme_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idjeux`),
  INDEX `fk_jeux_catégorie_idx` (`category_id` ASC),
  INDEX `fk_jeux_Plateforme1_idx` (`Plateforme_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC),
  UNIQUE INDEX `photo_UNIQUE` (`photo` ASC),
  UNIQUE INDEX `video_UNIQUE` (`video` ASC),
  CONSTRAINT `fk_jeux_catégorie`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`catégorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeux_Plateforme1`
    FOREIGN KEY (`Plateforme_id`)
    REFERENCES `mydb`.`Plateforme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
